import Foundation

/// Recognises build output by its shape, wherever it lives.
///
/// Xcode writes derived data wherever a project tells it to. Both of this Mac's
/// projects pass `-derivedDataPath build`, so an 11 GB tree of products, module
/// caches and indexes sits inside `~/Documents/Renewals` — where the Documents
/// scanner saw "a folder the user works in" and the Xcode scanner, which looks
/// only under `~/Library/Developer`, saw nothing at all. Position is the wrong
/// test. The layout is unmistakable, and that is what this checks.
///
/// Two shapes, and an aggregate of either:
/// - **Xcode derived data**: a `Build` directory beside `info.plist`,
///   `Index.noindex`, `ModuleCache.noindex` or `Logs`.
/// - **Swift package build**: a `.build` directory holding `workspace-state.json`,
///   or `build.db` beside `checkouts`.
/// - **An aggregate**: a directory named `build`, `.build` or `DerivedData` whose
///   every visible child is one of the above — one `build` folder per project,
///   holding one derived-data root per scheme, is exactly what
///   `-derivedDataPath build/<name>` produces.
///
/// A second family, **dependency stores**, is what lets a user drop an old
/// project's `node_modules` and keep the code beside it: a package manager's
/// installed dependencies or a tool's local environment, rebuilt from a manifest
/// (`node_modules`, `Pods`, a Python venv, a Cargo `target`). They stay with their
/// project — listed as regenerable rows under Documents & Files, where the user
/// judges — while Xcode and SwiftPM output goes to the Xcode category, which can
/// call it safe.
///
/// Everything recognised here is regenerated by the next build or install. Nothing
/// here is source: a folder that fails the shape test is left alone, however it is
/// named — a `target` folder without a `Cargo.toml` or `pom.xml` beside it is
/// somebody's folder called "target".
public enum BuildOutputDetector {

    public enum Kind: Sendable, Equatable {
        case xcodeDerivedData
        case swiftPackageBuild
        /// The label names the tool, e.g. "npm dependencies".
        case dependencyStore(String)

        public var label: String {
            switch self {
            case .xcodeDerivedData: "Xcode derived data"
            case .swiftPackageBuild: "Swift package build"
            case .dependencyStore(let tool): tool
            }
        }

        /// Xcode and SwiftPM output belongs to the Xcode category. Everything else
        /// stays with its project.
        public var isXcodeOutput: Bool {
            switch self {
            case .xcodeDerivedData, .swiftPackageBuild: true
            case .dependencyStore: false
            }
        }
    }

    public struct Root: Sendable, Equatable {
        public let url: URL
        public let kind: Kind
    }

    /// Names that only ever hold build output, so a folder so named whose contents
    /// pass the shape test is taken whole rather than root by root.
    private static let aggregateNames: Set<String> = ["build", ".build", "DerivedData"]

    /// Trees that are never descended: version control and vendored code, which
    /// are deep and are not build output. (Dependency stores are recognised
    /// *before* this list is consulted, so they are reported, not entered.)
    private static let opaqueNames: Set<String> = [".git", ".svn", ".hg", "vendor"]

    /// Hidden names that are looked at anyway. Everything else starting with a
    /// dot is somebody's configuration.
    private static let visibleHiddenNames: Set<String> = [".build", ".venv", ".tox", ".gradle"]

    public static func kind(of url: URL) -> Kind? {
        if isXcodeDerivedData(url) { return .xcodeDerivedData }
        if isSwiftPackageBuild(url) { return .swiftPackageBuild }
        if let tool = dependencyStore(url) { return .dependencyStore(tool) }

        guard aggregateNames.contains(url.lastPathComponent),
              let children = directories(in: url, includingHidden: false),
              !children.isEmpty,
              children.allSatisfy({ isXcodeDerivedData($0) || isSwiftPackageBuild($0) })
        else { return nil }
        return children.contains(where: isXcodeDerivedData) ? .xcodeDerivedData : .swiftPackageBuild
    }

    /// Build output found under `folder`, at most `maxDepth` levels down. A
    /// recognised root is reported once and not descended; `.build` is the one
    /// hidden name that is looked at.
    public static func roots(under folder: URL, maxDepth: Int = 2) -> [Root] {
        var found: [Root] = []
        func walk(_ directory: URL, depth: Int) {
            guard let children = directories(in: directory, includingHidden: true) else { return }
            for child in children {
                let name = child.lastPathComponent
                if name.hasPrefix("."), !visibleHiddenNames.contains(name) { continue }
                if let kind = kind(of: child) {
                    found.append(Root(url: child, kind: kind))
                    continue
                }
                if opaqueNames.contains(name) { continue }
                if depth < maxDepth { walk(child, depth: depth + 1) }
            }
        }
        walk(folder, depth: 1)
        return found.sorted { $0.url.path < $1.url.path }
    }

    // MARK: - Shapes

    static func isXcodeDerivedData(_ url: URL) -> Bool {
        guard isDirectory(url.appendingPathComponent("Build")) else { return false }
        return ["info.plist", "Index.noindex", "ModuleCache.noindex", "Logs"].contains {
            exists(url.appendingPathComponent($0))
        }
    }

    static func isSwiftPackageBuild(_ url: URL) -> Bool {
        guard url.lastPathComponent == ".build" else { return false }
        if exists(url.appendingPathComponent("workspace-state.json")) { return true }
        return exists(url.appendingPathComponent("build.db"))
            && isDirectory(url.appendingPathComponent("checkouts"))
    }

    /// The tool that owns a dependency store, or nil. Name plus a shape test
    /// wherever a bare name is ambiguous.
    static func dependencyStore(_ url: URL) -> String? {
        let name = url.lastPathComponent
        let parent = url.deletingLastPathComponent()
        switch name {
        case "node_modules":
            return "npm dependencies"
        case "Pods":
            return exists(url.appendingPathComponent("Manifest.lock")) ? "CocoaPods dependencies" : nil
        case ".venv", "venv":
            return exists(url.appendingPathComponent("pyvenv.cfg")) ? "Python environment" : nil
        case "__pycache__":
            return "Python bytecode cache"
        case ".tox":
            return "tox environments"
        case ".gradle":
            return "Gradle cache"
        case "bower_components":
            return "Bower dependencies"
        case "target":
            if exists(parent.appendingPathComponent("Cargo.toml")) { return "Cargo build output" }
            if exists(parent.appendingPathComponent("pom.xml")) { return "Maven build output" }
            return nil
        default:
            return nil
        }
    }

    private static func directories(in url: URL, includingHidden: Bool) -> [URL]? {
        guard let contents = try? FileManager.default.contentsOfDirectory(
            at: url, includingPropertiesForKeys: [.isDirectoryKey, .isSymbolicLinkKey],
            options: includingHidden ? [] : [.skipsHiddenFiles]
        ) else { return nil }
        return contents.filter {
            let values = try? $0.resourceValues(forKeys: [.isDirectoryKey, .isSymbolicLinkKey])
            return values?.isDirectory == true && values?.isSymbolicLink != true
        }
    }

    private static func exists(_ url: URL) -> Bool {
        FileManager.default.fileExists(atPath: url.path)
    }

    private static func isDirectory(_ url: URL) -> Bool {
        var isDirectory: ObjCBool = false
        return FileManager.default.fileExists(atPath: url.path, isDirectory: &isDirectory)
            && isDirectory.boolValue
    }
}
