import Foundation

/// Recognises build output by its shape, wherever it lives.
///
/// Xcode writes derived data wherever a project tells it to. Both of this Mac's
/// projects pass `-derivedDataPath build`, so an 11 GB tree of products, module
/// caches and indexes sits inside `~/Documents/Renewals` — where the Documents
/// scanner saw "a folder the user works in" and the Xcode scanner, which looks
/// only under `~/Library/Developer`, saw nothing at all. Position is the wrong
/// test. The layout is unmistakable, and that is what this checks.
///
/// Two shapes, and an aggregate of either:
/// - **Xcode derived data**: a `Build` directory beside `info.plist`,
///   `Index.noindex`, `ModuleCache.noindex` or `Logs`.
/// - **Swift package build**: a `.build` directory holding `workspace-state.json`,
///   or `build.db` beside `checkouts`.
/// - **An aggregate**: a directory named `build`, `.build` or `DerivedData` whose
///   every visible child is one of the above — one `build` folder per project,
///   holding one derived-data root per scheme, is exactly what
///   `-derivedDataPath build/<name>` produces.
///
/// A second family, **dependency stores**, is what lets a user drop an old
/// project's `node_modules` and keep the code beside it: a package manager's
/// installed dependencies or a tool's local environment, rebuilt from a manifest
/// (`node_modules`, `Pods`, a Python venv, a Cargo `target`). They stay with their
/// project — listed under Documents & Files, and called regenerable only on the
/// evidence `reinstallEvidence(for:)` finds — while Xcode and SwiftPM output goes to
/// the Xcode category, which can call it safe.
///
/// Everything recognised here is regenerated by the next build or install. Nothing
/// here is source: a folder that fails the shape test is left alone, however it is
/// named — a `target` folder without a `Cargo.toml` or `pom.xml` beside it is
/// somebody's folder called "target".
public enum BuildOutputDetector {

    public enum Kind: Sendable, Equatable {
        case xcodeDerivedData
        case swiftPackageBuild
        /// The label names the tool, e.g. "npm dependencies".
        case dependencyStore(String)

        public var label: String {
            switch self {
            case .xcodeDerivedData: "Xcode derived data"
            case .swiftPackageBuild: "Swift package build"
            case .dependencyStore(let tool): tool
            }
        }

        /// Xcode and SwiftPM output belongs to the Xcode category. Everything else
        /// stays with its project.
        public var isXcodeOutput: Bool {
            switch self {
            case .xcodeDerivedData, .swiftPackageBuild: true
            case .dependencyStore: false
            }
        }
    }

    public struct Root: Sendable, Equatable {
        public let url: URL
        public let kind: Kind
    }

    /// Names that only ever hold build output, so a folder so named whose contents
    /// pass the shape test is taken whole rather than root by root.
    private static let aggregateNames: Set<String> = ["build", ".build", "DerivedData"]

    /// Trees that are never descended: version control and vendored code, which
    /// are deep and are not build output. (Dependency stores are recognised
    /// *before* this list is consulted, so they are reported, not entered.)
    private static let opaqueNames: Set<String> = [".git", ".svn", ".hg", "vendor"]

    /// Hidden names that are looked at anyway. Everything else starting with a
    /// dot is somebody's configuration.
    private static let visibleHiddenNames: Set<String> = Set(
        [".build", ".venv", ".tox", ".gradle"] + taggedToolCaches.keys
    )

    /// Analysis caches that are recognised only when they carry their tool's
    /// `CACHEDIR.TAG` — see `CacheDirectoryTag`.
    ///
    /// mypy, pytest and ruff each write the tag into their cache and rebuild it from
    /// the sources beside it, with no network, so here the tag is both the shape test
    /// and the evidence. The name says where to look; without the tag a folder so
    /// named is somebody's folder.
    ///
    /// Three names and not "any tagged folder": `virtualenv` tags the environments it
    /// creates too, and a tagged `.venv` with no lockfile is exactly what
    /// `reinstallEvidence(for:)` refuses to call safe. The tag says "a tool made
    /// this and can make it again"; only knowing the tool says what again costs.
    ///
    /// None of the three was on this Mac on 20 Sep 2026. What was: SwiftPM's `.build`
    /// (tagged, and already recognised by `workspace-state.json`), uv's cache, and
    /// `~/.gradle/daemon`. Nothing under `~/Library/Caches` carried a tag at all, so
    /// there is no use for it there.
    static let taggedToolCaches: [String: String] = [
        ".mypy_cache": "mypy cache",
        ".pytest_cache": "pytest cache",
        ".ruff_cache": "ruff cache"
    ]

    public static func kind(of url: URL) -> Kind? {
        if isXcodeDerivedData(url) { return .xcodeDerivedData }
        if isSwiftPackageBuild(url) { return .swiftPackageBuild }
        if let tool = dependencyStore(url) { return .dependencyStore(tool) }

        guard aggregateNames.contains(url.lastPathComponent),
              let children = directories(in: url, includingHidden: false),
              !children.isEmpty,
              children.allSatisfy({ isXcodeDerivedData($0) || isSwiftPackageBuild($0) })
        else { return nil }
        return children.contains(where: isXcodeDerivedData) ? .xcodeDerivedData : .swiftPackageBuild
    }

    /// Build output found under `folder`, at most `maxDepth` levels down. A
    /// recognised root is reported once and not descended.
    ///
    /// Three levels, up from two on 20 Sep 2026. A workspace keeps its packages one
    /// folder down — `project/packages/api/node_modules` — so at two levels the
    /// commonest layout of all was never reached, and those stores stayed inside
    /// their project's bytes with no row of their own. Measured on this Mac with
    /// `scolo-cli scan`: 12.8–13.2 s at two levels, 12.8–12.9 s at three, the same
    /// rows either way. Dependency stores and version control are never entered,
    /// which is what keeps a deeper walk cheap.
    public static func roots(under folder: URL, maxDepth: Int = 3) -> [Root] {
        var found: [Root] = []
        func walk(_ directory: URL, depth: Int) {
            guard let children = directories(in: directory, includingHidden: true) else { return }
            for child in children {
                let name = child.lastPathComponent
                if name.hasPrefix("."), !visibleHiddenNames.contains(name) { continue }
                if let kind = kind(of: child) {
                    found.append(Root(url: child, kind: kind))
                    continue
                }
                if opaqueNames.contains(name) { continue }
                if depth < maxDepth { walk(child, depth: depth + 1) }
            }
        }
        walk(folder, depth: 1)
        return found.sorted { $0.url.path < $1.url.path }
    }

    // MARK: - Shapes

    static func isXcodeDerivedData(_ url: URL) -> Bool {
        guard isDirectory(url.appendingPathComponent("Build")) else { return false }
        return ["info.plist", "Index.noindex", "ModuleCache.noindex", "Logs"].contains {
            exists(url.appendingPathComponent($0))
        }
    }

    static func isSwiftPackageBuild(_ url: URL) -> Bool {
        guard url.lastPathComponent == ".build" else { return false }
        if exists(url.appendingPathComponent("workspace-state.json")) { return true }
        return exists(url.appendingPathComponent("build.db"))
            && isDirectory(url.appendingPathComponent("checkouts"))
    }

    /// The tool that owns a dependency store, or nil. Name plus a shape test
    /// wherever a bare name is ambiguous.
    static func dependencyStore(_ url: URL) -> String? {
        let name = url.lastPathComponent
        let parent = url.deletingLastPathComponent()
        if let label = taggedToolCaches[name] {
            return CacheDirectoryTag.isPresent(in: url) ? label : nil
        }
        switch name {
        case "node_modules":
            return "npm dependencies"
        case "Pods":
            return exists(url.appendingPathComponent("Manifest.lock")) ? "CocoaPods dependencies" : nil
        case ".venv", "venv":
            return exists(url.appendingPathComponent("pyvenv.cfg")) ? "Python environment" : nil
        case "__pycache__":
            return "Python bytecode cache"
        case ".tox":
            return "tox environments"
        case ".gradle":
            return "Gradle cache"
        case "bower_components":
            return "Bower dependencies"
        case "target":
            if exists(parent.appendingPathComponent("Cargo.toml")) { return "Cargo build output" }
            if exists(parent.appendingPathComponent("pom.xml")) { return "Maven build output" }
            return nil
        default:
            return nil
        }
    }

    // MARK: - Reinstall evidence

    /// The file beside a dependency store that says it can be put back as it was,
    /// or nil when nothing does.
    ///
    /// Recognising a store answers "what is this". It does not answer "is removing
    /// it safe", and for a while nothing asked: regenerable children began counting
    /// as safe on 18 Sep 2026, a store was a regenerable child on its name alone,
    /// and so every `node_modules` on the disk was promised as safe and ticked for
    /// the user. Reinstalling one needs the network and a record of what was
    /// installed. An abandoned project with no such record gets *different*
    /// dependencies back, or none, if a package has since been unpublished.
    ///
    /// The record has to be one **the installer wrote when it filled the store**,
    /// which is what makes it match: `package-lock.json`, `Podfile.lock`,
    /// `Cargo.lock`. A hand-kept `requirements.txt` is somebody's intention, not a
    /// record, so a Python environment needs a real lockfile. `bower_components`
    /// and `.tox` have no lockfile to find and are never safe.
    ///
    /// Three stores need no network at all and take their sources as evidence:
    /// `__pycache__` is compiled from the `.py` files beside it, a project's
    /// `.gradle` is rebuilt by the build script beside it (the downloaded
    /// dependencies live in `~/.gradle`), and a Maven `target` from the `pom.xml`
    /// that recognition already required, which pins its own versions.
    ///
    /// The store's own folder is searched first. For `node_modules` a workspace root
    /// is searched next — see `workspaceLockfile(for:within:)` — and nothing above
    /// `projectRoot`, the folder the scan is looking at, is ever consulted.
    ///
    /// The idea of asking for a lockfile is Purge's (`ReinstallSafetyEvaluator`,
    /// github.com/jithin-sabu/purge-app); the lists and the installer-wrote-it
    /// rule are this project's.
    public static func reinstallEvidence(for url: URL, within projectRoot: URL? = nil) -> String? {
        let parent = url.deletingLastPathComponent()
        func firstBeside(_ names: [String]) -> String? {
            names.first { exists(parent.appendingPathComponent($0)) }
        }
        if taggedToolCaches[url.lastPathComponent] != nil {
            // Rebuilt from the sources beside it; the tag is the tool's own word.
            return CacheDirectoryTag.isPresent(in: url) ? CacheDirectoryTag.fileName : nil
        }
        switch url.lastPathComponent {
        case "node_modules":
            return firstBeside(nodeLockfiles)
                ?? projectRoot.flatMap { workspaceLockfile(for: parent, within: $0) }
        case "Pods":
            return firstBeside(["Podfile.lock"])
        case ".venv", "venv":
            return firstBeside(["poetry.lock", "uv.lock", "Pipfile.lock", "pdm.lock"])
        case "target":
            // Cargo first, as in recognition: a folder with both files is Cargo's.
            if exists(parent.appendingPathComponent("Cargo.toml")) {
                return firstBeside(["Cargo.lock"])
            }
            return firstBeside(["pom.xml"])
        case ".gradle":
            return firstBeside([
                "settings.gradle", "settings.gradle.kts", "build.gradle", "build.gradle.kts"
            ])
        case "__pycache__":
            let sources = (try? FileManager.default.contentsOfDirectory(atPath: parent.path)) ?? []
            return sources.contains { $0.hasSuffix(".py") } ? "Python sources" : nil
        default:
            return nil
        }
    }

    private static let nodeLockfiles = [
        "package-lock.json", "npm-shrinkwrap.json", "yarn.lock",
        "pnpm-lock.yaml", "bun.lock", "bun.lockb"
    ]

    /// The lockfile of a workspace that covers `package`, or nil.
    ///
    /// npm, Yarn, pnpm and Bun workspaces keep **one** lockfile at the root for every
    /// package beneath it, so a package's own `node_modules` has none beside it and
    /// read "no lockfile" — true of the folder, false of the dependencies.
    ///
    /// A lockfile somewhere above is not evidence. A repository can hold a root
    /// lockfile for its tooling and, under `examples/`, a project installed on its
    /// own with nothing pinning it. The root has to *declare* a workspace, and the
    /// declaration has to name this package:
    ///
    /// * `package.json` → `"workspaces"`, an array of globs or `{ "packages": [...] }`
    ///   (npm, Yarn, Bun);
    /// * `pnpm-workspace.yaml` → a `packages:` list. The file existing is not enough:
    ///   `AnguriaStudio`'s on this Mac holds only `allowBuilds:` and declares nothing.
    ///
    /// `*` is one path component and `**` any number, as the tools read them; a
    /// pattern beginning `!` takes a package back out. The walk climbs from the
    /// package to `projectRoot` and no higher — a lockfile above the project belongs
    /// to something else.
    static func workspaceLockfile(for package: URL, within projectRoot: URL) -> String? {
        let rootPath = projectRoot.standardizedFileURL.path
        var directory = package.standardizedFileURL.deletingLastPathComponent()
        while directory.path == rootPath || directory.path.hasPrefix(rootPath + "/") {
            if let lockfile = nodeLockfiles.first(where: { exists(directory.appendingPathComponent($0)) }) {
                let relative = String(package.standardizedFileURL.path.dropFirst(directory.path.count + 1))
                if workspaceGlobs(at: directory).covers(relative) {
                    return "\(lockfile) at the workspace root"
                }
            }
            guard directory.path != rootPath else { break }
            directory = directory.deletingLastPathComponent()
        }
        return nil
    }

    private static func workspaceGlobs(at root: URL) -> [String] {
        var globs: [String] = []
        if let data = try? Data(contentsOf: root.appendingPathComponent("package.json")),
           let manifest = try? JSONSerialization.jsonObject(with: data) as? [String: Any] {
            if let list = manifest["workspaces"] as? [String] {
                globs += list
            } else if let object = manifest["workspaces"] as? [String: Any],
                      let list = object["packages"] as? [String] {
                globs += list
            }
        }
        if let text = try? String(contentsOf: root.appendingPathComponent("pnpm-workspace.yaml"),
                                  encoding: .utf8) {
            // The one shape the file takes: a top-level `packages:` key and the
            // `- 'glob'` items indented under it. Not a YAML parser, and it does not
            // need to be one: anything it cannot read names no package.
            var inPackages = false
            for line in text.split(whereSeparator: \.isNewline).map(String.init) {
                let trimmed = line.trimmingCharacters(in: .whitespaces)
                if !line.hasPrefix(" "), !line.hasPrefix("-") { inPackages = trimmed == "packages:" ; continue }
                guard inPackages, trimmed.hasPrefix("- ") else { continue }
                globs.append(trimmed.dropFirst(2).trimmingCharacters(in: CharacterSet(charactersIn: " '\"")))
            }
        }
        return globs
    }

    private static func directories(in url: URL, includingHidden: Bool) -> [URL]? {
        guard let contents = try? FileManager.default.contentsOfDirectory(
            at: url, includingPropertiesForKeys: [.isDirectoryKey, .isSymbolicLinkKey],
            options: includingHidden ? [] : [.skipsHiddenFiles]
        ) else { return nil }
        return contents.filter {
            let values = try? $0.resourceValues(forKeys: [.isDirectoryKey, .isSymbolicLinkKey])
            return values?.isDirectory == true && values?.isSymbolicLink != true
        }
    }

    private static func exists(_ url: URL) -> Bool {
        FileManager.default.fileExists(atPath: url.path)
    }

    private static func isDirectory(_ url: URL) -> Bool {
        var isDirectory: ObjCBool = false
        return FileManager.default.fileExists(atPath: url.path, isDirectory: &isDirectory)
            && isDirectory.boolValue
    }
}

private extension Array where Element == String {
    /// Whether these workspace globs name `path`, a package folder relative to the
    /// workspace root. Negations are read last, as the tools read them.
    func covers(_ path: String) -> Bool {
        func matches(_ glob: String) -> Bool {
            var pattern = glob
            while pattern.hasSuffix("/") { pattern.removeLast() }
            if pattern.hasPrefix("./") { pattern.removeFirst(2) }
            // `**` crosses path separators; a single `*` does not. `fnmatch` has no
            // `**`, so it is spelled `*` and matched without `FNM_PATHNAME`.
            if pattern.contains("**") {
                let loose = pattern.replacingOccurrences(of: "**", with: "*")
                return fnmatch(loose, path, 0) == 0
            }
            return fnmatch(pattern, path, FNM_PATHNAME) == 0
        }
        let included = filter { !$0.hasPrefix("!") }.contains(where: matches)
        let excluded = filter { $0.hasPrefix("!") }.contains { matches(String($0.dropFirst())) }
        return included && !excluded
    }
}
